/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "apiDb-dev",
            "region": "us-east-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-2:982e79b1-f54b-4ce9-b91b-09da5c39fd23",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_A7AcQXxHR",
    "aws_user_pools_web_client_id": "72bb91imt9alm14b1tlioqs4t6",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "apiEndpoints",
            "endpoint": "https://3tddhxo8u8.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://hxyfda5pfzf4zo65xperkzz5le.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-74ua3ptjz5dudghje755j25rom",
    "aws_mobile_analytics_app_id": "57becf686b8c4c47958e04a7b585d3db",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
